### ISSUE TITLE
Timer manager

### ISSUE THREAD

**Issue by Amaroq7** [Amaroq7/SPMod#10]
## Description
Timer manager should responsible for creating, executing, removing tasks.
Timer would be destroyed after finished execution (one time task) or by using ```Remove()```.
Timer with repeat flag could be destroyed returning ```PluginStop``` in its callback or by executing ```Remove()```.

Example plugin api:
```sourcepawn
enum TimerFlag
{
    None = 0,
    Repeat = (1<<0)
};

typeset TimerCallback
{
    function PluginReturn (Task task);
    function PluginReturn (Task task, any data);
};

methodmap Task
{
    Task(float time, TimerCallback func, any data = 0, TimerFlag flags = None);
    Remove();
    Trigger();
    Change(float interval, bool trigger = true);
};
```

- Operating system: n/a
- ReHLDS version: n/a
- Metamod version: n/a
- SPMod version: master

## How do we replicate the issue?
n/a

## Expected behavior (i.e. solution)
SPMod should expose api for plugins and modules to manage timers.

## Other Comments
n/a

**Comment by fant1kua** [comment]
My suggestion is to add pause and unpause methods . It can help us to show user HUD when user is alive (spawn) and pause it when he was dying.
