### ISSUE TITLE
camelCase or CamelCase styling for natives

### ISSUE THREAD

**Issue by Amaroq7** [Amaroq7/SPMod#5]
## Description
First natives use camelCase styling, but recently added ones #3 use CamelCase. I think we should decide which one we should go with. Personally I don't mind any of them, but I prefer to keep naming unified.

- Operating system: n/a
- ReHLDS version: n/a
- Metamod version: n/a
- SPMod version: master

## How do we replicate the issue?
n/a

## Expected behavior (i.e. solution)
We should go with camelCase or CamelCase styling for natives, not both.

## Other Comments
What are your thoughts?

**Comment by Mistrick** [comment]
I'm vote for CamelCase.

**Comment by Garey27** [comment]
I'm vote for CamelCase (In Source Pawn includes) - because SourceMod already use that styling for includes, so if someone will join us from SourceMod community or wanna work both of SPMod and SourceMod - can use CamelCase styling as regular.

**Comment by Phantomsq** [comment]
CamelCase, ofc

**Comment by FFx0q** [comment]
CamelCase bocie :)

**Comment by FFx0q** [comment]
CamelCase

**Comment by Amaroq7** [comment]
Natives will use CamelCase styling then. Is someone willing to do PR to address this issue?
