### ISSUE TITLE
Architecture changes

### ISSUE THREAD

**Issue by Mistrick** [Amaroq7/SPMod#50]
## Description

My suggestion is move binds for other languages to extentions, in core create only interfaces for another modules.
With this we can easier create binds for more languages(if someone will want add support for other language).

Question for discussion:
Maybe better develop metamod instead metaplugin for interfaces?

**Comment by Langert1337** [comment]
Curl pls

**Comment by Amaroq7** [comment]
> Maybe better develop metamod instead metaplugin for interfaces?
Could you elaborate? Should we develop new metamod or use as a base existing one? What would be the benefits of this move?

**Comment by Mistrick** [comment]
For start i think use as a base, leave existing interfaces and parallel develop new.
In future we can replace old interfaces to new.
Benefits are remove one level.
Current state(considering the first suggestion):
`engine->metamod->spmod->extention with other language->plugin`
With first suggestion and move to metamod level we'll get:
`engine->metamod->plugin with other language->plugin`

**Comment by Amaroq7** [comment]
Which metamod would the best to use as a base? As we know there are a few available on the net.
